### ISSUE TITLE
Layout [v2] issues and progress

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#4618]
Firefly III features a new *experimental* layout that will in time replace the current layout. In this issue I will track and manage issues. 

**Enabling the new layout**
Set `FIREFLY_III_LAYOUT=v2` and Firefly III will show you the new layout where it's available.

**More info**
I'm writing code using the 80/20 rule: 80% of the work will take 20% of the time and vice versa. As such, I am not (yet) interested in fine-tuning everything and making sure that it works 100%. Rather, I'm aiming for 80% so I can keep churning out pages and updating the necessary API calls and code. So if you run into some problem, keep in mind I might put it on the back burner in favor of some other work.

**Reporting issues**
Feel free to open issues yourself or tell me any other way what you're running into. I will keep track of them below, together with the status:

**Issues so far**
*Issues with a checkbox have been fixed or a fix is available in the next release*

- [ ] You can't see or test the new layout on the demo site.
- [ ] #4556 Auto-calculate from total when splitting expense
- [x] #4589 Cannot edit Source or Destination Accounts on transactions in Layout V2
- [x] #4591 Creating / Editing Split Transactions 
- [x] #4592 Wrong balance with layout V2
- [x] #4608 Automatic blank time field for new transactions to avoid manual intervention
- [x] #4609 Entering transactions is less satisfying in V2
- [x] #4611 Not all categories show up in the category box on v2
- [x] #4614 Cannot View Inactive Accounts on V2
- [ ] #4618 New layout doesn't jump to next month
- [x] #4620 Expense accounts only work with double chars

**Comment by JC5** [comment]
**In 5.5.6**

- [ ] Can't submit edit/create transaction form with Enter.
- [ ] Edit form doesn't work.
- [ ] Test data still visible.

**Comment by JC5** [comment]
In **5.5.7

- #4656 layout wont load accounts

**Comment by JC5** [comment]
In **5.5.8**

- [ ] #4685 dashboard chart wont refresh twice

**Comment by JC5** [comment]
**5.5.9**

- #4717 Need better titles for boxes.
- #4715 Better look for empty boxes.

**Comment by JC5** [comment]
**5.5.10**

- [ ] #4735
