### ISSUE TITLE
Creating transfer transactions broken in 5.6.9 with v2 layout ('cannot handle "Todo"')

### ISSUE THREAD

**Issue by Styleflix** [firefly-iii/firefly-iii#5481]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After I updated Firefly to the new version 5.6.9 today, I cannot create transfer transactions anymore (v2 layout).
Deposit and withdrawal transactions still work but regardless which accounts I choose or which details I set, after clicking "store transaction" for a transfer transaction an error pops up and below "Destination Account" showing the message "AccountValidator::validateDestination cannot handle "Todo", so it will always return false."

### Expected behaviour

After filling out all required information the transaction should be saved.

### Debug information

Debug information generated at 2022-01-03 16:55:57 Europe/Amsterdam for Firefly III version **5.6.9**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.9 |
| Firefly III API | 1.5.5 |
| Build | 66
, 02-01-2022 08:12:35 CET
 |
| PHP | 8.0.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | de5a88fc-4cc6-4da2-a5d0-c468a4b1529f |
| Using docker? | true |
| Layout | v2 |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | de_DE |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2022-01-01 00:00:00 |
| Session end | 2022-01-31 23:59:59 |
| Session first |  |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0 |

### Steps to reproduce

1. Go to "Accounting" > "Transfers" and click the button "Create a new transaction"
2. Enter a description, source and destination account and the amount
3. Click "store transaction"
4. The transaction will not be safed but the error appears below the "destination account" field

### Additional info

I also recognized that behind the title "Transactions" there is a text "breadcrumbs.create_todo" visible (that applies to to withdrwals and deposits as well). I don't know if this is connected to this issue but since both showing something with "todo" I thought I mention it.
I also am aware that the v2 layout won't be developed any further but since this is a rather severe bug I hope it can get fixed before v3 gets released.
Thanks for your work!

Here is a screenshot of the error:
![Firefly-iii_error_transactions](https://user-images.githubusercontent.com/81714586/147953340-a761b635-346b-49c3-aea4-6c06be16b598.png)

**Comment by JC5** [comment]
As per the warning on top of the page, v2 will not be continued. This bug will also not be fixed, unfortunately.
