### ISSUE TITLE
Administration management endpoints

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#7315]
Firefly III will feature multi-administration management: the ability to manage multiple administrations. You can do user management, access rights, etc. This **epic** collects and manages all tickets that need to be finished before this can be a reality. This work is being done in conjunction with #6331. The ability for API endpoints to be administration-sensitive will follow in the relevant tickets.

```[tasklist]
### Tasks
- [ ] Ability to CRUD new administrations
- [ ] Ability to manage access rights per administration
- [ ] Ability to send out invites for administrations
```
